### ISSUE TITLE
Reactive Controller doesn't 'reset'

### ISSUE THREAD

**Issue by morgz** [itchingpixels/talks#3]
Starting the timer the first time, requires both pan and rotate.

However, interacting with it the second time activates the timer with only a pan or a rotate and doesn't require both. It seems as though the .begin is already satisfied from the previous interaction.

**Comment by almostintuitive** [comment]
Yeah:(

Instead of merge, or combineLatest, we should use zip. I originally wanted to keep the number of concepts introduced as low as possible, and I overlooked lots of things, but it's good that you picked it up:).

Let me fix this, hopefully later today!
In the meantime, if you're curious, have a look at zip, it does exactly what we need in this scenario.

Thanks a lot!

**Comment by fabb** [comment]
Unit tests would be awesome. I tried a bit, but i am struggling to create a common test interface that both fits the imperative and reactive versions.

**Comment by almostintuitive** [comment]
@fabb: I think with @morgz pull request #2 we'll have a standard interface between both to write unit tests with.

I'll merge it in in a second!

**Comment by almostintuitive** [comment]
done!

**Comment by fabb** [comment]
nah, i meant something like this:
https://github.com/fabb/talks/blob/unit_tests/functional-reactive-intuition/Project/RFP/GestureReactor.swift

not yet finished though. and it needs `Variable`

**Comment by almostintuitive** [comment]
:+1: nice!

**Comment by fabb** [comment]
Lets see, that way you can't directly use the gesture recognizer signal. And i still need to figure out how to mock the timer for testing, probably injecting a timer generator.
But i guess that makes the code more complicated, opposed to the point of the article ;-)

**Comment by almostintuitive** [comment]
I've changed combineLatest to zip in 9fed2db6b5eb5b4bae23c044fe1d2871318441e7

**Comment by morgz** [comment]
Nice one. I'll check it out tomorrow... Just working on converting an open source ReactiveCocoa pro to RxSwift to learn.

**Comment by almostintuitive** [comment]
@fabb 's unit tests reveal a bunch of inconsistencies between the imperative and the reactive version though, and those have not been fixed! just FYI :)

**Comment by fabb** [comment]
@itchingpixels Please reopen, the reset still does not work correctly (see also #4). Reproduction:
- Start Pan Gesture
- End Pan Gesture
- Start Rotate Gesture
  => Timer starts counting, but it should not.

After having spent some time thinking, I guess it is not possible to use separate `panStarted` and `panEnded` signals for solving this problem. Maybe it would rather be necessary to have the full `pan` and `rotate` stream and combine them with `zip` where we check, if the state of both gestures is `.Began` (or `.Changed` I guess, here it gets complicated).

**Comment by almostintuitive** [comment]
sure:).
I'll have time later this week to look into this!

**Comment by almostintuitive** [comment]
yeah, unfortunately the current dividing of gestures won't work as expected:(

**Comment by morgz** [comment]
@itchingpixels Hopefully fixed that in this [PR](https://github.com/itchingpixels/talks/pull/6)

**Comment by almostintuitive** [comment]
@morgz , @fabb : both of you now have push access to the repo by the way:)

**Comment by almostintuitive** [comment]
@morgz : thanks!
